name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Push events to matching v*.*.* (e.g., v1.0.0, v1.2.3)

# Added permissions needed for creating releases
permissions:
  contents: write

jobs:
  build:
    name: Build and Create Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Build release binary
        run: cargo build --release --target x86_64-pc-windows-msvc
      
      - name: Get the version
        id: get_version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Smoothie Queuer v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            target/x86_64-pc-windows-msvc/release/smoothie-queuer.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}